services:
  app:
    image: andrearavasi1/riftcards:latest
    container_name: riftcards_app    
    ports:
      - "3001:3000"
    restart: unless-stopped
    
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
